config/routes.rb
Rails.application.routes.draw do
  resources :group_messages, only: [:index, :create]
  post 'group_messages/get_messages_by_room'
  post 'group_messages/load_group_messages'
  post 'group_messages/users_chat'
  post 'group_messages/one_to_one_chat'
  get 'group_messages/user_messaging'
  get 'group_messages/download_files'
  get 'user_wallet_transactions/create_wallet'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'tasks/task_fund_info'

  resources :group_messages do
    get :autocomplete_user_name, :on => :collection
  end
  get 'group_messages/search_user'
  post 'projects/send_project_invite_email'
  post 'tasks/send_email'
  post 'projects/send_project_email'
  post 'projects/start_project_by_signup'
  get 'projects/get_activities'
  get 'projects/show_all_tasks'
  get 'projects/show_all_teams'
  get 'projects/show_all_revision'
  get 'projects/show_task'
  # resources :task_attachments, only: [:index, :new, :create, :destroy]
  post 'task_attachments/create'
  post 'task_attachments/destroy_attachment'
  get 'assignments/update_collaborator_invitation_status'
  resources :profile_comments, only: [:index, :create, :update, :destroy]
  resources :plans
  resources :cards

  resources :notifications, only: [:index, :destroy] do
    collection do
      get :load_older
    end
  end

  resources :teams do
    collection do
      get :users_search
    end
  end

  resources :admin_invitations, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :admin_requests, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :apply_requests, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :team_memberships, only: [:update, :destroy]
  resources :work_records
  get 'wallet_transactions/new'
  post 'wallet_transactions/create'
  get 'user_wallet_transactions/new'
  get 'user_wallet_transactions/download_keys'
  post 'user_wallet_transactions/create'
  get 'payment_notifications/create'
  get 'proj_admins/new'
  get 'proj_admins/create'
  get 'proj_admins/destroy'
  resources :proj_admins do
    member do
      get :accept, :reject
    end
  end
  resources :assignments do
    member do
      get :accept, :reject, :completed, :confirmed, :confirmation_rejected
    end
  end
  resources :payment_notifications
  resources :donations

  resources :do_for_frees do
    member do
      get :accept, :reject
    end
  end

  resources :do_requests do
    member do
      get :accept, :reject
    end
  end

  resources :activities, only: [:index]
  resources :wikis
  resources :tasks do
    member do
      get :accept, :reject, :doing, :reviewing, :completed
      delete '/members/:team_membership_id', to: 'tasks#removeMember', as: :remove_task_member
    end
  end

  resources :discussions, only: [:destroy, :accept] do
    member do
      get :accept
    end
  end

  resources :favorite_projects, only: [:create, :destroy]
  resources :home , controller: 'projects'
  resources :projects, :except => [:edit] do
    resources :tasks do
      member do
        get :card_payment, to: 'payments/stripe#new'
        post :card_payment, to: 'payments/stripe#create'
      end
      resources :task_comments
      resources :assignments
    end

    resources :project_comments

    member do
      get :accept, :reject
      post :follow
      get :unfollow
      post :rate
      get :discussions
      get :revisions
      post :switch_approval_status
      get :plan
      get :read_from_mediawiki
      post :write_to_mediawiki
      get :revision_action
      get :unblock_user
      get :block_user
    end

    collection do
      get :autocomplete_user_search
      get :archived
      post :change_leader
      get :get_in
    end

    member do
      get :taskstab, as: :taskstab
      get :show_project_team, as: :show_project_team
    end
  end

  resources :change_leader_invitation, only: [:create] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  get '/projects/search_results', to: 'projects#search_results'
  post '/projects/user_search', to: 'projects#user_search'
  post '/projects/:id/save-edits', to: 'projects#saveEdit'
  post '/projects/:id/update-edits', to: 'projects#updateEdit'

  get "/oauth2callback" => "projects#contacts_callback"
  get "/callback" => "projects#contacts_callback"
  get '/contacts/failure' => "projects#failure"
  get '/contacts/gmail'
  get '/contacts/yahoo'
  get '/pages/privacy_policy'
  get '/pages/terms_of_use'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    member do
     get  :my_wallet
    end
  end

  get 'my_projects', to: 'users#my_projects', as: :my_projects
  root to: 'visitors#landing'
end

app/models/group_message.rb
class GroupMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :chatroom
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
end

app/controllers/group_messages_controller.rb
class GroupMessagesController < ApplicationController
#  require 'GroupMessagesHelper'
  autocomplete :user, :name, :full => true
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  before_action :set_group_message, only: [:show, :edit, :update, :destroy]
  before_action :validate_chat_room_users, only: [:create]

  layout 'dashboard', only: [:index, :user_messaging]

  def validate_user_messages_by_project(id)
    # user_ids = Project.find(id).team.team_memberships.collect(&:team_member_id)
    user_ids = Project.find(id).chatroom.groupmembers.collect(&:user_id)
    if !(user_ids.include? current_user.id)
      return false
    end
    return true
  end

  def search_user

    @user = current_user
    if params[:search]
      @user = User.name_like("%#{params[:search]}%").order('name')
    else
    end
  end

  def load_messages_by_chatroom(id)
    chat_room = Chatroom.find(id) rescue nil
    project = Project.find(chat_room.project_id) rescue nil
    if project.blank?
      if chat_room.user_id == current_user.id || chat_room.friend_id == current_user.id
        return true
      end
      return false
    else
      if chat_room.blank? || !(chat_room.user_id == current_user.id || chat_room.friend_id == current_user.id || (chat_room.groupmembers.collect(&:user_id).include? current_user.id))
        return false
      end
      return true
    end
  end

  def validate_chat_room_users
    return if !load_messages_by_chatroom(params['group_message']['chatroom_id'])
  end

  def index
    user_teams_id = current_user.team_memberships.collect(&:team_id)
    user_project_ids = Team.find(user_teams_id).collect(&:project_id)
    @user_projects = Project.find (user_project_ids)
    @user_projects = @user_projects + current_user.projects
    if @user_projects.blank?
      @group_messages = []
    else
      @user_projects = @user_projects.uniq
      pid1 = @user_projects.first.id
      chatroom = Chatroom.where(project_id: pid1)
      @team_members = chatroom.first.groupmembers
      @group_messages = GroupMessage.where(chatroom_id: chatroom.first.id)
      @chatroom = chatroom.first.id
    end
    one_to_one_chatrooms = Chatroom.where("project_id is NULL AND ( (user_id = ? OR friend_id = ? ) )", current_user.id, current_user.id)
    ids = one_to_one_chatrooms.collect(&:user_id)
    ids = ids + one_to_one_chatrooms.collect(&:friend_id)
    ids = ids.uniq
    @one_to_one_chat_users = User.find(ids)
  end

  def show
  end

  def user_messaging

    user = User.find(params[:user_id]) rescue nil
    if user.blank?
      redirect_to group_messages_path
    else
      user_id = params[:user_id]
      chatroom = Chatroom.where("project_id is NULL AND ( (user_id = ? AND friend_id = ? ) OR ( user_id = ? AND friend_id = ?  ) )", current_user.id, user_id, user_id, current_user.id) rescue nil
      if chatroom.blank?
        chat= Chatroom.create(user_id: user_id, friend_id: current_user.id)
        #Groupmember.create(chatroom_id: chat.id, user_id: current_user.id)
        #Groupmember.create(chatroom_id: chat.id, user_id: user_id)
        @chatroom = chat.id
      else
        @chatroom = chatroom.first.id
      end
      user_teams_id = current_user.team_memberships.collect(&:team_id)
      user_project_ids = Team.find(user_teams_id).collect(&:project_id)
      @user_projects = Project.find (user_project_ids)
      if @user_projects.blank?
        @group_messages = []
      else
        @user_projects = @user_projects.uniq
        pid1 = @user_projects.first.id
        chatroom = Chatroom.where(project_id: pid1)
        @team_members = chatroom.first.groupmembers

      end
      @group_messages = GroupMessage.where(chatroom_id: @chatroom)
      one_to_one_chatrooms = Chatroom.where("project_id is NULL AND ( (user_id = ? OR friend_id = ? ) )", current_user.id, current_user.id)
      ids = one_to_one_chatrooms.collect(&:user_id)
      ids = ids + one_to_one_chatrooms.collect(&:friend_id)
      ids = ids.uniq
      @one_to_one_chat_users = User.find(ids)
      render :index
    end


  end

  # GET /group_messages/new
  def one_to_one_chat
    user_id = params[:user_id]
    chatroom = Chatroom.where("project_id is NULL AND ( (user_id = ? AND friend_id = ? ) OR ( user_id = ? AND friend_id = ?  ) )", current_user.id, user_id, user_id, current_user.id) rescue nil
    if chatroom.blank?
      chat= Chatroom.create(user_id: user_id, friend_id: current_user.id)
      Groupmember.create(chatroom_id: chat.id, user_id: current_user.id)
      Groupmember.create(chatroom_id: chat.id, user_id: user_id)
      @chatroom = chat.id
    else
      @chatroom = chatroom.first.id
    end
    @group_messages = GroupMessage.where(chatroom_id: @chatroom)
    respond_to :js
  end

  def users_chat
    user_id = params[:user_id]
    project_id = params[:project_id]
    if validate_user_messages_by_project(project_id)
      chatroom = Chatroom.where("project_id = ? AND ( (user_id = ? AND friend_id = ? ) OR ( user_id = ? AND friend_id = ?  ) )", project_id, current_user.id, user_id, user_id, current_user.id) rescue nil
      if chatroom.blank?
        chat=Chatroom.create(project_id: project_id, user_id: user_id, friend_id: current_user.id)

        @chatroom = chat.id
      else
        @chatroom = chatroom.first.id
      end
      @group_messages = GroupMessage.where(chatroom_id: @chatroom)
      respond_to :js
    end
  end

  def download_files
    group_message = GroupMessage.find(params[:id])
    if load_messages_by_chatroom (group_message.chatroom_id)
      if group_message.attachment.blank?
        redirect_to group_messages_path
      else
        data = open(group_message.attachment.file.url)
        send_data data.read, filename:group_message.attachment.file.filename, stream: 'true'
       # redirect_to group_message.attachment.file.url
       # send_file group_message.attachment.to_s
      end
    else
      redirect_to group_messages_path
    end
  end

  def get_messages_by_room
    if validate_user_messages_by_project (params[:id])
      chatroom = Chatroom.where(project_id: params[:id])
      @team_members = chatroom.first.groupmembers
      @group_messages = GroupMessage.where(chatroom_id: chatroom.first.id)
      @chatroom = chatroom.first.id
      respond_to :js
    end
  end

  def load_group_messages
    if load_messages_by_chatroom(params[:id])
      @group_messages = GroupMessage.where(chatroom_id: params[:id]).last(25)
      respond_to :js
    end
  end

  def new
    @group_message = GroupMessage.new
  end

  # GET /group_messages/1/edit
  def edit
  end

  def create
    @group_message = GroupMessage.new(group_message_params)
    if (@group_message.message.blank? && @group_message.attachment.blank?)
      @group_message = nil
    else
      @group_message.user_id = current_user.id
      respond_to do |format|
        if @group_message.save
          format.json { render :show, status: :created, location: @group_message }
          format.js
        else
          format.json { render json: @group_message.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @group_message.update(group_message_params)
        format.json { render :show, status: :ok, location: @group_message }
      else
        format.json { render json: @group_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group_message.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group_message
    @group_message = GroupMessage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_message_params
    params.require(:group_message).permit(:message, :user_id, :chatroom_id, :attachment)
  end

end

app/helpers/group_messages_helper.rb
module GroupMessagesHelper

def get_chatroom_name(chatroom_id)
  chat_room = Chatroom.find(chatroom_id)
  unless chat_room.blank?
   if (chat_room.user_id.nil? and chat_room.friend_id.nil?)
      Project.find(chat_room.project_id).title rescue 'Project Title Not Found.'
    else
      User.select(:name).where(id: [chat_room.user_id, chat_room.friend_id]).collect(&:name).inspect rescue 'Direct Messages'
    end
  end
end

end

app/views/group_messages/_all_messages.html.erb
<% unless @group_messages.blank? %>
    <% @group_messages.each do |message| %>
        <div class="row message">
          <div class="message-sender">
            <a href="#">
              <% if message.user.picture? %>
                  <%= image_tag(message.user.picture, class: "profile-image") %>
              <% else %>
                  <%= gravatar_for(message.user, 35) %>
              <% end %>
            </a>
          </div>
          <div class="message-content">

            <div class="message-text">
              <%= message.message %>
              <% if message.attachment? %>
                  <br>
                  <% if %w{jpg png jpg gif bmp}.include?(message.attachment.file.extension) %>
                      <%= image_tag message.attachment.url %>
                      <br>
                      Download
                      image: <%= link_to message.attachment.file.filename, group_messages_download_files_path(id: message.id)%>
                  <% else %>
                      Download
                      file: <%= link_to message.attachment.file.filename, group_messages_download_files_path(id: message.id) %>
                  <% end %>
                  <br>
                  <br>
              <% end %>
            </div>
            <span class="name"><%= message.user.try(:name) %></span>
            <span class="message-date"><%= time_ago_in_words(message.created_at) %></span>
            <br>

          </div>
        </div>
    <% end %>
<% else %>
    <div class="row message">
      <div class="message-content">
        No Messages
      </div>
    </div>
<% end %>

app/views/group_messages/_chatroom_info.html.erb
<div class="row margin-none">
  <!-- Chatroom name -->
  <div class="small-6 columns">
    <h4>
      <%= get_chatroom_name(@chatroom) rescue 'Not Found' %>
    </h4>
    <div id="message-load-image" style="text-align: center; display: none">
      <%= image_tag 'loading.gif' %>
    </div>
  </div>
  <div class="small-6 columns">
    <!-- Search box -->
    <div class="small-8 columns">
      <form>
        <div class="row messages-page-row collapse">
          <div class="small-9 columns">
            <input type="search" placeholder="search">
          </div>
          <div class="small-3 columns">
            <span class="postfix"><i class="fa fa-search" aria-hidden="true"></i></span>
          </div>
        </div>
      </form>
    </div>
    <!-- Settings and attach file icons -->
    <div class="small-4 columns">
              <span style="margin-right: 8px;">
                <!--<i class="fa fa-cog fa-2x" title="Settings" aria-hidden="true"></i>-->
              </span>
              <span>
                <!--<i class="fa fa-paperclip fa-2x" title="Attach file" aria-hidden="true"></i>-->
              </span>
    </div>
  </div>
</div>

app/views/group_messages/_form.html.erb
<div class="message-form-wrapper">

  <div class="message-sender">
    <% if current_user.picture? %>
        <%= image_tag(current_user.picture, size: "30x30") %>
    <% else %>
        <%= gravatar_for_user(current_user) %>
    <% end %>
  </div>

  <%= simple_form_for(@group_message = GroupMessage.new, :remote => true, :html => {:class => 'new-message-form'}) do |f| %>
      <div class="form-group">
        <div id="load-image-gif" style="text-align: center; display: none">
          <%= image_tag 'loading.gif' %>
        </div>
        <%= f.hidden_field :chatroom_id, value: @chatroom rescue 0 %>
        <%= f.text_area :message, :placeholder => 'Write message' %>
        <%= f.file_field :attachment, :style => 'display:none', id: 'file-attachment-button' %>
        <%= f.submit 'Send', id: 'submit-message' %>
      </div>
      <div class="attach-group">
        <span class="postfix text-default">
          <i class="fa fa-paperclip fa-2x" title="Attach file" aria-hidden="true" id="file-attachment-icon"></i>
          Add Attachment
        </span>
      </div>
  <% end %>

</div>

<script>
  $("#group_message_message").keypress(function (e) {
    if (e.which == 13 && !e.shiftKey) {
      if ($(this).val().trim() == "") {
        return false
      }
      else {
        $("#submit-message").trigger('click');
      }
    }
  });
  $("#file-attachment-icon").click(function (e) {

    $("#file-attachment-button").click();

  });
  $("#file-attachment-button").change(function () {
    $("#submit-message").click();
    $("#load-image-gif").show();
  });
  $("#submit-message").click(function (event) {
    if (($('#file-attachment-button').val() == "" && $('#group_message_message').val() == "")) {
      event.preventDefault();
    }

  });
</script>

app/views/group_messages/_new_message.html.erb
<% unless @group_message.blank? %>
    </hr>

    <div class="row message">
      <div class="message-sender">
        <a href="#">
          <% if @group_message.user.picture? %>
              <%= image_tag(@group_message.user.picture, class: "profile-image") %>
          <% else %>
              <%= gravatar_for(@group_message.user, 35) %>
          <% end %>
        </a>
      </div>
      <div class="message-content">
        <div class="message-text"><%= @group_message.message %>
          <% if @group_message.attachment? %>
              <br>
              <% if %w{jpg png jpg gif bmp}.include?(@group_message.attachment.file.extension) %>
                  <%= image_tag @group_message.attachment.url %>
                  <br>
                  Download
                  image: <%= link_to @group_message.attachment.file.filename, group_messages_download_files_path(id: @group_message.id) %>
              <% else %>
                  Download
                  file: <%= link_to @group_message.attachment.file.filename, group_messages_download_files_path(id: @group_message.id) %>
              <% end %>
              <br>
              <br>
          <% end %>
        </div>
        <span class="name"><%= @group_message.user.try(:name) %></span>
        <span class="message-date"><%= time_ago_in_words(@group_message.created_at) %></span>
        <br>
      </div>
    </div>
<% end %>

app/views/group_messages/_one_to_one_members.html.erb
<% unless @one_to_one_chat_users.blank? %>
    <% @one_to_one_chat_users.each do |user| %>
        <li>
          <a href="#" class="one-user-chat" id="<%= user.id %>" name=""> <%= user.name %> </a>
        </li>
    <% end %>
<% end %>
<script>
  $(".one-user-chat").click(function () {
    $("div#message-load-image").show();
    user_id = $(this).attr('id');
    project_id = $(this).attr('name');
    $.ajax({
      url: "/group_messages/one_to_one_chat",
      type: "post",
      data: {user_id: user_id},
      success: function () {
      }
    });
  });
</script>

app/views/group_messages/_project_team.html.erb
<% unless @team_members.blank? %>
    <% @team_members.each do |user| %>
        <li>
          <a href="#" class="project-user-chat" id="<%= user.user_id %>" name="<%= user.chatroom.project_id %>"> <%= user.user.name %> </a>
        </li>
    <% end %>
<% end %>

<script>
  $(".project-user-chat").click(function () {
    $("div#message-load-image").show();
    user_id = $(this).attr('id');
    project_id = $(this).attr('name');
    $.ajax({
      url: "/group_messages/users_chat",
      type: "post",
      data: {project_id: project_id, user_id: user_id},
      success: function () {
      }
    });
  });
</script>

app/views/group_messages/create.js.erb
$("#messages").append("<%= escape_javascript(render('group_messages/new_message'))%>");
$("#group_message_message").val(' ');
$('#messages').scrollTop(1E10)
$("div#message-load-image").hide();
$("#file-attachment-button").val('');
$("#load-image-gif").hide();

app/views/group_messages/edit.html.erb
<h1>Editing Group Message</h1>
<%= render 'form' %>
<%= link_to 'Show', @group_message %> |
<%= link_to 'Back', group_messages_path %>

app/views/group_messages/get_messages_by_room.js.erb
$("#chat-name").html("");
$("#chat-name").html("<%= escape_javascript(render('group_messages/chatroom_info')) %>");

$("#messages").html("");
$("#messages").html("<%= escape_javascript(render('group_messages/all_messages')) %>");
$("#message-form-div").html("")
$("#message-form-div").html("<%= escape_javascript(render('group_messages/form')) %>");
$("#project-team-members").html("")
$("#project-team-members").html("<%= escape_javascript(render('group_messages/project_team')) %>");
$("div#message-load-image").hide();

app/views/group_messages/index.html.erb
<script>
  $(document).ready(function () {
    $("#user-search").click(function () {
      $("#display-user").toggle();
    });
  });
</script>
<div class="row group-messages-wrapper margin-none">
  <div class="col-lg-4 col-md-4 col-sm-4 group-messages-nav" id="messages-nav">
    <div class="messages-nav-title">
      Team Messages
    </div>
    <div class="messages-menu">
      <div class="messages-submenu">
        <!-- <div class="submenu-title">
          <% current_user_projects = @user_projects rescue nil %>
          <span class="menu-subtitle">PROJECTS (<%= @user_projects.count rescue 0 %>)</span>
        </div> -->
        <ul>
          <% unless @user_projects.blank? %>
              <% @user_projects.each.with_index do |project, index| %>
                  <% if index == 0 %>
                      <li>
                        <a href="#" class="projects-chat" id="<%= project.id %>"><%= project.try(:title) %></a>
                      </li>
                  <% else %>
                      <li><a href="#" class="projects-chat" id="<%= project.id %>"><%= project.try(:title) %></a></li>
                  <% end %>
              <% end %>
          <% end %>
        </ul>
      </div>
      <div class="messages-submenu" id="chatrooms_id">
        <div class="submenu-title">
          <span class="menu-subtitle">DIRECT MESSAGES</span>
        </div>
        <ul class="circle" id="project-team-members">
          <%= render 'group_messages/project_team' %>
        </ul>
        <div class="submenu-title">
          <span class="menu-subtitle">Message Other Than Team</span>
          <!--<i class="fa fa-plus-circle" aria-hidden="true"></i>-->
        </div>
        <ul class="circle" id="project-team-members">
          <%= render 'group_messages/one_to_one_members' %>
        </ul>
      </div>
      <div class="search-users" id="user-search">
        <span data-toggle="modal" data-target="#searchUser"><i class="fa fa-plus"></i>&nbsp;&nbsp;Search for user</span>
      </div>
      <div id="display-user" class="display-none">
        <%= form_tag(group_messages_search_user_path, :method => "get", remote: true, id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: "search-query", placeholder: "Find or Start a conversation", data: {autocomplete: autocomplete_user_name_group_messages_path, :id_element => '#some_element'} %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-8 col-md-8 col-sm-8 group-messages-content" id="page-message-content">
    <div id="chat-name">
      <%= render partial: 'group_messages/chatroom_info', locals: {chat_id: @chatroom} %>
    </div>
    <div id="messages">
      <%= render 'group_messages/all_messages' %>
    </div>
    <div id='message-form-div'>
      <% unless @chatroom.blank? %>
          <%= render 'group_messages/form' %>
      <% else %>
          <div> you are not member of any chat room</div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
  function load_messages() {
    var chatroom_id = $("#group_message_chatroom_id").val();
    if (chatroom_id != undefined) {
      $.ajax({
        url: "/group_messages/load_group_messages",
        type: "post",
        data: {id: chatroom_id},
        success: function () {
          $('#messages').scrollTop(1E10)
        }
      });
    }
  }
  $(document).ready(function () {
    $.ajaxSetup({cache: false});
    window.setInterval(function () {
      load_messages();
    }, 5000);
    $(".projects-chat").click(function () {
      project_id = $(this).attr('id')
      $("div#message-load-image").show();
      callAjax(project_id);
    });
    function callAjax(project_id) {
      $.ajax({
        url: "/group_messages/get_messages_by_room",
        type: "post",
        data: {id: project_id},
        success: function () {
        }
      });
    }
  });
  $('#search').bind('railsAutocomplete.select', function (event, data) {
    if (data.item.id != '')
      window.location.href = '/group_messages/user_messaging?user_id=' + data.item.id
  });
</script>

app/views/group_messages/new.html.erb
<h1>New Group Message</h1>
<%= render 'form' %>
<%= link_to 'Back', group_messages_path %>

app/views/group_messages/one_to_one_chat.js.erb
$("#chat-name").html("");
$("#chat-name").html("<%= escape_javascript(render('group_messages/chatroom_info')) %>");
$("#messages").html(" ");
$("#messages").html("<%= escape_javascript(render('group_messages/all_messages')) %>");
$("#message-form-div").html(" ")
$("#message-form-div").html("<%= escape_javascript(render('group_messages/form')) %>");
$("div#message-load-image").hide();

app/views/group_messages/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Message:</strong>
  <%= @group_message.message %>
</p>
<p>
  <strong>User:</strong>
  <%= @group_message.user %>
</p>
<p>
  <strong>Chatroom:</strong>
  <%= @group_message.chatroom %>
</p>
<%= link_to 'Edit', edit_group_message_path(@group_message) %> |
<%= link_to 'Back', group_messages_path %>

app/views/group_messages/users_chat.js.erb
$("#chat-name").html("");
$("#chat-name").html("<%= escape_javascript(render('group_messages/chatroom_info')) %>");
$("#messages").html(" ");
$("#messages").html("<%= escape_javascript(render('group_messages/all_messages')) %>");
$("#message-form-div").html(" ")
$("#message-form-div").html("<%= escape_javascript(render('group_messages/form')) %>");
$("div#message-load-image").hide();