config/routes.rb
Rails.application.routes.draw do
  resources :group_messages, only: [:index, :create]
  post 'group_messages/get_messages_by_room'
  post 'group_messages/load_group_messages'
  post 'group_messages/users_chat'
  post 'group_messages/one_to_one_chat'
  get 'group_messages/user_messaging'
  get 'group_messages/download_files'
  get 'user_wallet_transactions/create_wallet'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'tasks/task_fund_info'

  resources :group_messages do
    get :autocomplete_user_name, :on => :collection
  end
  get 'group_messages/search_user'
  post 'projects/send_project_invite_email'
  post 'tasks/send_email'
  post 'projects/send_project_email'
  post 'projects/start_project_by_signup'
  get 'projects/get_activities'
  get 'projects/show_all_tasks'
  get 'projects/show_all_teams'
  get 'projects/show_all_revision'
  get 'projects/show_task'
  # resources :task_attachments, only: [:index, :new, :create, :destroy]
  post 'task_attachments/create'
  post 'task_attachments/destroy_attachment'
  get 'assignments/update_collaborator_invitation_status'
  resources :profile_comments, only: [:index, :create, :update, :destroy]
  resources :plans
  resources :cards

  resources :notifications, only: [:index, :destroy] do
    collection do
      get :load_older
    end
  end

  resources :teams do
    collection do
      get :users_search
    end
  end

  resources :admin_invitations, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :admin_requests, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :apply_requests, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :team_memberships, only: [:update, :destroy]
  resources :work_records
  get 'wallet_transactions/new'
  post 'wallet_transactions/create'
  get 'user_wallet_transactions/new'
  get 'user_wallet_transactions/download_keys'
  post 'user_wallet_transactions/create'
  get 'payment_notifications/create'
  get 'proj_admins/new'
  get 'proj_admins/create'
  get 'proj_admins/destroy'
  resources :proj_admins do
    member do
      get :accept, :reject
    end
  end
  resources :assignments do
    member do
      get :accept, :reject, :completed, :confirmed, :confirmation_rejected
    end
  end
  resources :payment_notifications
  resources :donations

  resources :do_for_frees do
    member do
      get :accept, :reject
    end
  end

  resources :do_requests do
    member do
      get :accept, :reject
    end
  end

  resources :activities, only: [:index]
  resources :wikis
  resources :tasks do
    member do
      get :accept, :reject, :doing, :reviewing, :completed
      delete '/members/:team_membership_id', to: 'tasks#removeMember', as: :remove_task_member
    end
  end

  resources :discussions, only: [:destroy, :accept] do
    member do
      get :accept
    end
  end

  resources :favorite_projects, only: [:create, :destroy]
  resources :home , controller: 'projects'
  resources :projects, :except => [:edit] do
    resources :tasks do
      member do
        get :card_payment, to: 'payments/stripe#new'
        post :card_payment, to: 'payments/stripe#create'
      end
      resources :task_comments
      resources :assignments
    end

    resources :project_comments

    member do
      get :accept, :reject
      post :follow
      get :unfollow
      post :rate
      get :discussions
      get :revisions
      post :switch_approval_status
      get :plan
      get :read_from_mediawiki
      post :write_to_mediawiki
      get :revision_action
      get :unblock_user
      get :block_user
    end

    collection do
      get :autocomplete_user_search
      get :archived
      post :change_leader
      get :get_in
    end

    member do
      get :taskstab, as: :taskstab
      get :show_project_team, as: :show_project_team
    end
  end

  resources :change_leader_invitation, only: [:create] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  get '/projects/search_results', to: 'projects#search_results'
  post '/projects/user_search', to: 'projects#user_search'
  post '/projects/:id/save-edits', to: 'projects#saveEdit'
  post '/projects/:id/update-edits', to: 'projects#updateEdit'

  get "/oauth2callback" => "projects#contacts_callback"
  get "/callback" => "projects#contacts_callback"
  get '/contacts/failure' => "projects#failure"
  get '/contacts/gmail'
  get '/contacts/yahoo'
  get '/pages/privacy_policy'
  get '/pages/terms_of_use'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    member do
     get  :my_wallet
    end
  end

  get 'my_projects', to: 'users#my_projects', as: :my_projects
  root to: 'visitors#landing'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  enum action: [
      :default,
      :became_project_admin,
      :lost_project_admin_status,
      :created_project,
      :updated_project,
      :become_project_admin_invitation,
      :admin_request,
      :reject_admin_invitation,
      :accept_admin_invitation,
      :reject_admin_request,
      :accept_admin_request,
      :suggested_task,
      :pending_do_request,
      :leader_change,
      :apply_requset,
      :accept_apply_request,
      :reject_apply_request
  ]

  belongs_to :user
  belongs_to :origin_user, :foreign_key => 'origin_user_id', :class_name => 'User'
  belongs_to :source_model, polymorphic: true

  validates :user, presence: true
  validates :source_model, presence: true

  def self.unread
    where(:read => false)
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  layout "dashboard"

  PER_LOAD_COUNT = 10

  def index
    @notifications = Notification.last(PER_LOAD_COUNT)
    Notification.where(:read => false).update_all(:read => true)
  end

  def load_older
    @notifications = current_user.notifications.where("id < ?", params[:first_notification_id]).last(PER_LOAD_COUNT)
    if !@notifications.empty?
      @all_notifications_displayed = @notifications.first.id == current_user.notifications.first.id ? true : false
    else
      @all_notifications_displayed = true
    end
    @all_notifications_displayed = false
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    respond_to do |format|
      if @notification.destroy
        format.json { render json: @notification.id, status: :ok }
      else
        format.json { render status: :internal_server_error }
      end
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_load_older_link.html.erb
<% if notifications.count > 0 %>
    <div class="load-older-notifications-link">
      <i class="fa fa-tags" aria-hidden="true"></i>
      <%= link_to "Load older", load_older_notifications_path(first_notification_id: notifications.first.id), remote: true %>
    </div>
<% end %>

app/views/notifications/_notification.html.erb
<%= render partial: "notifications/#{notification.source_model_type.underscore}/#{notification.action}",
           layout: "notification_layout",
           locals: { notification: notification }
%>

app/views/notifications/_notification_layout.html.erb
<div id="notification-<%= notification.id %>" class="invitation notify-card">
  <div class="notify-mark">
    <i class="fa fa-bell-o" aria-hidden="true"></i>
  </div>
  <div class="notify-content">
    <span class="date"><%= "#{notification.created_at.strftime(" %b")} #{notification.created_at.day.ordinalize}" rescue nil %></span>
    <div class="notify-body">
      <div class="notification-body">
        <span><%= yield %></span>
      </div>
      <%= render partial: "notifications/#{notification.source_model_type.underscore}/accept_reject_buttons", locals: { notification: notification }%>
    </div>
  </div>
</div>

app/views/notifications/_notifications_menu.html.erb
<div class="medium-3 small-12 columns">
    <div class="row">
      <div class="not-list">
        <ul class="Notifi">
          <li class="not"><h4 class="header"> <i class="fa fa-bell-o" aria-hidden="true"></i>Notificatons <i class="fa fa-cog"></i></h4> </li>
        </ul>
        
         <ul class="Notifi-text">
          <li class="not">
            <div class="pro">PROJECT ALERT</div>
            <div class="pro-text">Lorem Ipsem dolor sit amet, conscteture adipiscing elit, sed diam nonummy nibh euismod</div>
            <div class="pro-we">WE SERVE <span>MAY 29TH</span></div>
          </li>         
         </ul>
         
         <ul class="Notifi-1">
          <li class="not">
            <div class="pro">TEAM INVITATION</div>
            <div class="pro-text">Lorem Ipsem dolor sit amet, conscteture adipiscing elit, sed diam nonummy nibh euismod</div>
            <div class="pro-we">WE SERVE <span>MAY 29TH</span></div>
          </li>         
         </ul>
         
         <ul class="Notifi-active">
          <li class="not">
            <div class="pro">TEAM INVITATION</div>
            <div class="pro-text">Lorem Ipsem dolor sit amet, conscteture adipiscing elit, sed diam nonummy nibh euismod</div>
            <div class="pro-we">CAJU<span>MAY 29TH</span></div>
          </li>         
         </ul>
      </div>
    </div>
  </div>

app/views/notifications/index.html.erb
<% content_for :title do %>
  My notifications
<% end %>

<div class="notifications-wrapper">
  <h2>Notificaitons</h2>
  <a href="javascript:void(0)" class="mark-read">
    <i class="fa fa-check"></i>&nbsp;&nbsp;Mark all as read
  </a>

  <%= render partial: 'load_older_link', locals: { notifications: @notifications } %>
  <%= render @notifications %>
</div>

<script>
  $(function() {
    JsonFormsHelper.InitializeNotificationsControls();
    // $(".notifications-container").scrollTop($(".notifications-container")[0].scrollHeight);
  });
</script>

app/views/notifications/load_older.js.erb
$('.notifications-container').prepend('<%= escape_javascript(render @notifications) %>');
$('.load-older-notifications-link').remove();
JsonFormsHelper.InitializeNotificationsControls();

<% if !@notifications.empty? %>
  $(".notifications-container").scrollTo("notification-<%= @notifications.last.id %>");
<% end %>

<% if !@all_notifications_displayed %>
  $('.notifications-container').prepend('<%= escape_javascript( render partial: 'load_older_link',
                                                                        locals: { notifications: @notifications } ) %>');
<% end %>