config/routes.rb
Rails.application.routes.draw do
  resources :group_messages, only: [:index, :create]
  post 'group_messages/get_messages_by_room'
  post 'group_messages/load_group_messages'
  post 'group_messages/users_chat'
  post 'group_messages/one_to_one_chat'
  get 'group_messages/user_messaging'
  get 'group_messages/download_files'
  get 'user_wallet_transactions/create_wallet'
  get 'pages/terms_of_use'
  get 'pages/privacy_policy'
  get 'tasks/task_fund_info'

  resources :group_messages do
    get :autocomplete_user_name, :on => :collection
  end
  get 'group_messages/search_user'
  post 'projects/send_project_invite_email'
  post 'tasks/send_email'
  post 'projects/send_project_email'
  post 'projects/start_project_by_signup'
  get 'projects/get_activities'
  get 'projects/show_all_tasks'
  get 'projects/show_all_teams'
  get 'projects/show_all_revision'
  get 'projects/show_task'
  # resources :task_attachments, only: [:index, :new, :create, :destroy]
  post 'task_attachments/create'
  post 'task_attachments/destroy_attachment'
  get 'assignments/update_collaborator_invitation_status'
  resources :profile_comments, only: [:index, :create, :update, :destroy]
  resources :plans
  resources :cards

  resources :notifications, only: [:index, :destroy] do
    collection do
      get :load_older
    end
  end

  resources :teams do
    collection do
      get :users_search
    end
  end

  resources :admin_invitations, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :admin_requests, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :apply_requests, only: [:create] do
    member do
      post :accept, :reject
    end
  end

  resources :team_memberships, only: [:update, :destroy]
  resources :work_records
  get 'wallet_transactions/new'
  post 'wallet_transactions/create'
  get 'user_wallet_transactions/new'
  get 'user_wallet_transactions/download_keys'
  post 'user_wallet_transactions/create'
  get 'payment_notifications/create'
  get 'proj_admins/new'
  get 'proj_admins/create'
  get 'proj_admins/destroy'
  resources :proj_admins do
    member do
      get :accept, :reject
    end
  end
  resources :assignments do
    member do
      get :accept, :reject, :completed, :confirmed, :confirmation_rejected
    end
  end
  resources :payment_notifications
  resources :donations

  resources :do_for_frees do
    member do
      get :accept, :reject
    end
  end

  resources :do_requests do
    member do
      get :accept, :reject
    end
  end

  resources :activities, only: [:index]
  resources :wikis
  resources :tasks do
    member do
      get :accept, :reject, :doing, :reviewing, :completed
      delete '/members/:team_membership_id', to: 'tasks#removeMember', as: :remove_task_member
    end
  end

  resources :discussions, only: [:destroy, :accept] do
    member do
      get :accept
    end
  end

  resources :favorite_projects, only: [:create, :destroy]
  resources :home , controller: 'projects'
  resources :projects, :except => [:edit] do
    resources :tasks do
      member do
        get :card_payment, to: 'payments/stripe#new'
        post :card_payment, to: 'payments/stripe#create'
      end
      resources :task_comments
      resources :assignments
    end

    resources :project_comments

    member do
      get :accept, :reject
      post :follow
      get :unfollow
      post :rate
      get :discussions
      get :revisions
      post :switch_approval_status
      get :plan
      get :read_from_mediawiki
      post :write_to_mediawiki
      get :revision_action
      get :unblock_user
      get :block_user
    end

    collection do
      get :autocomplete_user_search
      get :archived
      post :change_leader
      get :get_in
    end

    member do
      get :taskstab, as: :taskstab
      get :show_project_team, as: :show_project_team
    end
  end

  resources :change_leader_invitation, only: [:create] do
    member do
      get 'accept'
      get 'reject'
    end
  end

  get '/projects/search_results', to: 'projects#search_results'
  post '/projects/user_search', to: 'projects#user_search'
  post '/projects/:id/save-edits', to: 'projects#saveEdit'
  post '/projects/:id/update-edits', to: 'projects#updateEdit'

  get "/oauth2callback" => "projects#contacts_callback"
  get "/callback" => "projects#contacts_callback"
  get '/contacts/failure' => "projects#failure"
  get '/contacts/gmail'
  get '/contacts/yahoo'
  get '/pages/privacy_policy'
  get '/pages/terms_of_use'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    member do
     get  :my_wallet
    end
  end

  get 'my_projects', to: 'users#my_projects', as: :my_projects
  root to: 'visitors#landing'
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:notes, :todos, :owner, :status, :body)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= simple_form_for(@plan) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :notes %>
    <%= f.input :todos %>
    <%= f.input :owner %>
    <%= f.input :status %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plans</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Todos</th>
      <th>Owner</th>
      <th>Status</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.notes %></td>
        <td><%= plan.todos %></td>
        <td><%= plan.owner %></td>
        <td><%= plan.status %></td>
        <td><%= plan.body %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @plan.notes %>
</p>

<p>
  <strong>Todos:</strong>
  <%= @plan.todos %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @plan.owner %>
</p>

<p>
  <strong>Status:</strong>
  <%= @plan.status %>
</p>

<p>
  <strong>Body:</strong>
  <%= @plan.body %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>